SPLASHES = [
    "The moon is not a planet",
    "meg = chad",
    "Ayy Yep!",
    "What's my purpose?",
    "MCPI_SPEEDHACK",
    "MCPIL-Revival",
    "Minescripters",
    "Made in the UK!!",
    "I use ChadPi BTW",
    "Snowball",
    "Robo",
    "If I could, I would. But I can't, so I shan't.",
    "SyntaxError: invalid syntax",
    "We Fixed The Rail!",
    "The World Of Notch!",
    "github.com/PythonScratcher/ChadPi!",
    "Now with fly-hacks!",
    "Now with custom skins!",
    "@Banana",
    "BANANA!",
    'To "Na" Or Not To "Na", that is the question!',
    "Not Minecraft Java!",
    "Oh yeah, that version...",
    "Segmentation fault (core dumped)",
    "It's the Segment's Fault!",
    "Who is meg?",
    "(Not) Made by Notch!",
    "Open-Source!",
    "By PythonScratcher",
    "This is randomly generated",
    "Meg > StevePi > Steve",
    "RIP all MCPILs, 2020-2022",
    "Watch out for Meg!",
    "Didn't remove Herobrine!",
    "Check out PBPT Anarchy!",
    "你好中国",
    "한국 안녕하세요!",
    "日本ハロー！",
    "Привет Россия!",
    "Підтримай Україну!",
    "Supercalifragilisticexpialidocious!",
    "Now with multiplayer!",
    "RED EXE ENGINEER GAMING",
    "Play Minecraft Pi Edition, watch Red-Exe-Engineer, get PIG!",
    "Wat",
    "About the same size as ur mom",
    "meg",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "technically PE!",
    "ChadPi > Planet",
    "Based From Planet!!!1",
    "Hello United States",
    "Hello UK!",
    "Bonjour France",
    "Bonjour/Hello Canada",
    "Hola España",
    "Hallo Deutschland",
    "Ciao Italia",
    "Olá Portugal",
    "Привет Россия",
    "こんにちは日本",
    "안녕하세요 대한민국",
    "你好中国",
    "Namaste भारत",
    "Merhaba Türkiye",
    "مرحباً البلدان الناطقة بالعربية",
    "Sawubona iNingizimu Afrika",
    "Jambo Kenya",
    "Habari Tanzania",
    "Kumusta Pilipinas",
    "Xin chào Việt Nam",
    "Ayubowan ශ්‍රී ලංකාව",
    "Moïen Lëtzebuerg",
    "Donate to UKRAINE! www.unicef.org",
    
]
