SPLASHES = [
    "The moon is not a planet",
    "meg = chad",
    "Ayy Yep!",
    "What's my purpose?",
    "MCPI_SPEEDHACK",
    "MCPIL-Revival",
    "Minescripters",
    "I use ChadPi BTW",
    "Snowball",
    "Robo",
    "If I could, I would. But I can't, so I shan't.",
    "SyntaxError: invalid syntax",
    "We Fixed The Rail!",
    "The World Of Notch!",
    "github.com/PythonScratcher/ChadPi!",
    "Now with fly-hacks!",
    "Now with custom skins!",
    "@Banana",
    "BANANA!",
    'To "Na" Or Not To "Na", that is the question!',
    "Not Minecraft Java!",
    "Oh yeah, that version...",
    "Segmentation fault (core dumped)",
    "It's the Segment's Fault!",
    "Who is meg?",
    "(Not) Made by Notch!",
    "Open-Source!",
    "RIP all MCPILs, 2020-2022",
    "Watch out for StevePi!",
    "Didn't remove Herobrine!",
    "Check out PBPT Anarchy!",
    "你好中国",
    "한국 안녕하세요!",
    "日本ハロー！",
    "Привет Россия!",
    "Підтримай Україну!",
    "Supercalifragilisticexpialidocious!",
    "Now with multiplayer!",
    "RED EXE ENGINEER GAMING",
    "Play Minecraft Pi Edition, watch Red-Exe-Engineer, get PIG!",
    "Wat",
    "About the same size as ur mom",
    "meg",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "technically PE!",
    "ChadPi > Planet",
    "Based From Planet!!!1",
]
